apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-developers
  name: app-developers
  namespace: apps
spec:
  containers:
  - image: pliniogsnascimento/rinha-de-backend-q3
    name: app-developers
  dnsPolicy: ClusterFirst
  restartPolicy: Always
