apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-developers
    argocd.argoproj.io/instance: k8s-app-challenge
  name: app-developers
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: app-developers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-developers
  name: app-developers
  namespace: apps
spec:
  selector:
    matchLabels:
      app: app-developers
  template:
    metadata:
      labels:
        app: app-developers
    spec:
      containers:
      - image: pliniogsnascimento/rinha-de-backend-q3
        name: app-developers
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: app-developers
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
data:
  config.yaml: |
    db:
      host: postgres.db
      port: 5432
      user: postgres
      password: mysecretpassword
      database: rinha_backend
      defaultMaxConns: 8

    server:
      port: "9090"
      rateLimiting:
        enable: true
        rate: 100
        tokenBurst: 50
kind: ConfigMap
metadata:
  namespace: apps
  name: app-developers
