apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
    tier: db
  name: postgres
  namespace: db
spec:
  selector:
    matchLabels:
      app: postgres
      tier: db
  template:
    metadata:
      labels:
        app: postgres
        tier: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: POSTGRES_DB
          value: rinha_backend
        image: postgres
        name: postgres
        resources: {}
        ports:
        - containerPort: 5432
          name: port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: db
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
    tier: db
